### ISSUE TITLE
Loss of highlighting when using hyperlinks with spaces

### ISSUE THREAD

**Issue by flipacholas** [KFreon/hugo-vscode-shortcode-syntax-highlighting#1]
Hi, many thanks for your plugin.

I've just discovered that the markdown highlighter doesn't mark the label of hyperlinks (`[hello](http://hello.com)`) any more when using a shortcode as hyperlink and the label contain spaces.

To reproduce: `[example with spaces]({{< ref "something" >}})`
Expected: Same behaviour as `[example_without_spaces]({{< ref "something" >}})`

**Comment by ghost** [comment]
While I can confirm that behaviour, it looks to be an issue in the VSCode highlighter.
Mine only affects things within the hugo syntax e.g. `{{< stuff in here only >}}`.
You can confirm by disabling my extension and seeing the same behaviour.

Now, it's likely due to markdown not allowing hrefs to have spaces in them (cos it's invalid), but the hugo syntax allows it. 
i.e. This doesn't work in the standard VSCode highlighter `[this has spaces](http://www.spaces and stuff.com)`
But this does: `[this has spaces](http://www.nospaces.com)`

I don't know that I want to expand my extension to overtake syntax that exists in the main markdown syntax, but if you have any ideas on how that could be done, let me know.

Sorry I can't be more helpful :(
